/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slniecko;

import java.awt.EventQueue;
import java.io.IOException;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Unlink
 */
public class Game extends javax.swing.JFrame {

    private int pocetObjektov;
    private String obrazok;

    private int skore;
    private final Timer casovac;
    
    /**
     * Creates new form Hra
     * @param pocetObjektov
     * @param obrazok
     */
    public Game(int pocetObjektov, String obrazok) throws IOException {
        initComponents();
        this.pocetObjektov = pocetObjektov;
        this.obrazok = obrazok;
        this.skore = 0;
        PlayArea p = new PlayArea(this, 500, 500);
        this.contentPanel.add(p);
        this.pack();
        casovac = new Timer(20, p);
        this.startGame();
    }
    
    public void editScore(int ako) {
        skore += ako;
        skoreLabel.setText(skore+"");
    }

    public void startGame() {
        casovac.start();
    }

    public void pauseGame() {
        casovac.stop();
    }

    public int getPocetObjektov() {
        return pocetObjektov;
    }

    public String getObrazok() {
        return obrazok;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        skoreLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slniecko");

        jLabel1.setText("Skóre:");

        skoreLabel.setText("0");

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skoreLabel)
                        .addGap(0, 344, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(skoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int pocetObjektov = 20;
        String imgUrl = null;
        if (args.length > 0) {
            pocetObjektov = Integer.parseInt(args[0]);
        }
        if (args.length > 1) {
            imgUrl = args[1];
        }

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }

        final int pocetObjektovFinal = pocetObjektov;
        final String imgUrlFinal = imgUrl;
        
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Game hra = new Game(pocetObjektovFinal, imgUrlFinal);
                    hra.setVisible(true);
                } catch (IOException ex) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel skoreLabel;
    // End of variables declaration//GEN-END:variables
}
